version: "3"
services:
  # reverseproxy:
  #   build:
  #     context: /udagram-reverseproxy/docker
  #   image: nguyenbason/reverseproxy 
  backend_user:
    build:
      context: udagram-api-user
    image: nguyenbason/udagram-api-user
  backend_feed:
    build:
      context: /udagram-api-feed  
    image: nguyenbason/udagram-api-feed
  frontend:
    build:
      context: /udagram-frontend  
    image: nguyenbason/udacity-frontend
